trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python36Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.6'
      Python36Windows:
        imageName: 'windows-2019'
        python.version: '3.6'
      Python37Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.7'
      Python37Windows:
        imageName: 'windows-latest'
        python.version: '3.7'
      Python37Mac:
        imageName: 'macos-latest'
        python.version: '3.7'
      Python38Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.8'
      Python38Windows:
        imageName: 'windows-latest'
        python.version: '3.8'
      Python38Mac:
        imageName: 'macos-latest'
        python.version: '3.8'
      Python39Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.9'
      Python39Windows:
        imageName: 'windows-latest'
        python.version: '3.9'
      Python39Mac:
        imageName: 'macos-latest'
        python.version: '3.9'
      Python310Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.10'
      Python310Windows:
        imageName: 'windows-latest'
        python.version: '3.10'
      Python310Mac:
        imageName: 'macos-latest'
        python.version: '3.10'
      Python311Linux:
        imageName: 'ubuntu-latest'
        python.version: '3.11.0-rc.2'
      Python311Windows:
        imageName: 'windows-latest'
        python.version: '3.11.0-rc.2'
      Python311Mac:
        imageName: 'macos-latest'
        python.version: '3.11.0-rc.2'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
      allowUnstable: true

  - script: |
      python -m pip install --upgrade pip setuptools
    displayName: 'Install dependencies'

  - script: |
      pip install --prefer-binary -e .
    displayName: 'Install (python 2.7/3.5: prefer binary)'
    condition: or(eq(variables['python.version'], '2.7'), eq(variables['python.version'], '3.5'))

  - script: |
      pip install -e .
    displayName: 'Install'
    condition: not(or(eq(variables['python.version'], '2.7'), eq(variables['python.version'], '3.5')))

  - script: |
      pip install -r requirements.txt --prefer-binary
      python -m pytest thinc
    displayName: 'Run tests'
